################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/condition.c \
/home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_device.c \
/home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_init.c \
/home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_io.c \
/home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_shmem.c \
/home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/time.c 

OBJS += \
./Middlewares/OpenAMP/libmetal/generic/condition.o \
./Middlewares/OpenAMP/libmetal/generic/generic_device.o \
./Middlewares/OpenAMP/libmetal/generic/generic_init.o \
./Middlewares/OpenAMP/libmetal/generic/generic_io.o \
./Middlewares/OpenAMP/libmetal/generic/generic_shmem.o \
./Middlewares/OpenAMP/libmetal/generic/time.o 

C_DEPS += \
./Middlewares/OpenAMP/libmetal/generic/condition.d \
./Middlewares/OpenAMP/libmetal/generic/generic_device.d \
./Middlewares/OpenAMP/libmetal/generic/generic_init.d \
./Middlewares/OpenAMP/libmetal/generic/generic_io.d \
./Middlewares/OpenAMP/libmetal/generic/generic_shmem.d \
./Middlewares/OpenAMP/libmetal/generic/time.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/OpenAMP/libmetal/generic/condition.o: /home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/condition.c Middlewares/OpenAMP/libmetal/generic/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DCORE_CM4 -DUSE_FULL_LL_DRIVER -DNO_ATOMIC_64_SUPPORT -DUSE_HAL_DRIVER -DSTM32MP157Cxx -DMETAL_INTERNAL -DMETAL_MAX_DEVICE_REGIONS=2 -DVIRTIO_SLAVE_ONLY -D__LOG_TRACE_IO_ -c -I../../../Inc -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -I../../../../../../../../Drivers/BSP/STM32MP15xx_DISCO -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32MP1xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/OpenAMP/libmetal/generic/generic_device.o: /home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_device.c Middlewares/OpenAMP/libmetal/generic/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DCORE_CM4 -DUSE_FULL_LL_DRIVER -DNO_ATOMIC_64_SUPPORT -DUSE_HAL_DRIVER -DSTM32MP157Cxx -DMETAL_INTERNAL -DMETAL_MAX_DEVICE_REGIONS=2 -DVIRTIO_SLAVE_ONLY -D__LOG_TRACE_IO_ -c -I../../../Inc -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -I../../../../../../../../Drivers/BSP/STM32MP15xx_DISCO -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32MP1xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/OpenAMP/libmetal/generic/generic_init.o: /home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_init.c Middlewares/OpenAMP/libmetal/generic/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DCORE_CM4 -DUSE_FULL_LL_DRIVER -DNO_ATOMIC_64_SUPPORT -DUSE_HAL_DRIVER -DSTM32MP157Cxx -DMETAL_INTERNAL -DMETAL_MAX_DEVICE_REGIONS=2 -DVIRTIO_SLAVE_ONLY -D__LOG_TRACE_IO_ -c -I../../../Inc -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -I../../../../../../../../Drivers/BSP/STM32MP15xx_DISCO -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32MP1xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/OpenAMP/libmetal/generic/generic_io.o: /home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_io.c Middlewares/OpenAMP/libmetal/generic/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DCORE_CM4 -DUSE_FULL_LL_DRIVER -DNO_ATOMIC_64_SUPPORT -DUSE_HAL_DRIVER -DSTM32MP157Cxx -DMETAL_INTERNAL -DMETAL_MAX_DEVICE_REGIONS=2 -DVIRTIO_SLAVE_ONLY -D__LOG_TRACE_IO_ -c -I../../../Inc -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -I../../../../../../../../Drivers/BSP/STM32MP15xx_DISCO -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32MP1xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/OpenAMP/libmetal/generic/generic_shmem.o: /home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/generic_shmem.c Middlewares/OpenAMP/libmetal/generic/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DCORE_CM4 -DUSE_FULL_LL_DRIVER -DNO_ATOMIC_64_SUPPORT -DUSE_HAL_DRIVER -DSTM32MP157Cxx -DMETAL_INTERNAL -DMETAL_MAX_DEVICE_REGIONS=2 -DVIRTIO_SLAVE_ONLY -D__LOG_TRACE_IO_ -c -I../../../Inc -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -I../../../../../../../../Drivers/BSP/STM32MP15xx_DISCO -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32MP1xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/OpenAMP/libmetal/generic/time.o: /home/matteo/STM32MPU_workspace/STM32MP1-Ecosystem-v5.0.0/Developer-Package/STM32Cube_FW_MP1_V1.6.0/Middlewares/Third_Party/OpenAMP/libmetal/lib/system/generic/time.c Middlewares/OpenAMP/libmetal/generic/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DCORE_CM4 -DUSE_FULL_LL_DRIVER -DNO_ATOMIC_64_SUPPORT -DUSE_HAL_DRIVER -DSTM32MP157Cxx -DMETAL_INTERNAL -DMETAL_MAX_DEVICE_REGIONS=2 -DVIRTIO_SLAVE_ONLY -D__LOG_TRACE_IO_ -c -I../../../Inc -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -I../../../../../../../../Drivers/BSP/STM32MP15xx_DISCO -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc -I../../../../../../../../Drivers/STM32MP1xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32MP1xx/Include -I../../../../../../../../Drivers/CMSIS/Include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/open-amp/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/libmetal/lib/include -I../../../../../../../../Middlewares/Third_Party/OpenAMP/virtual_driver -Og -ffunction-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-OpenAMP-2f-libmetal-2f-generic

clean-Middlewares-2f-OpenAMP-2f-libmetal-2f-generic:
	-$(RM) ./Middlewares/OpenAMP/libmetal/generic/condition.cyclo ./Middlewares/OpenAMP/libmetal/generic/condition.d ./Middlewares/OpenAMP/libmetal/generic/condition.o ./Middlewares/OpenAMP/libmetal/generic/condition.su ./Middlewares/OpenAMP/libmetal/generic/generic_device.cyclo ./Middlewares/OpenAMP/libmetal/generic/generic_device.d ./Middlewares/OpenAMP/libmetal/generic/generic_device.o ./Middlewares/OpenAMP/libmetal/generic/generic_device.su ./Middlewares/OpenAMP/libmetal/generic/generic_init.cyclo ./Middlewares/OpenAMP/libmetal/generic/generic_init.d ./Middlewares/OpenAMP/libmetal/generic/generic_init.o ./Middlewares/OpenAMP/libmetal/generic/generic_init.su ./Middlewares/OpenAMP/libmetal/generic/generic_io.cyclo ./Middlewares/OpenAMP/libmetal/generic/generic_io.d ./Middlewares/OpenAMP/libmetal/generic/generic_io.o ./Middlewares/OpenAMP/libmetal/generic/generic_io.su ./Middlewares/OpenAMP/libmetal/generic/generic_shmem.cyclo ./Middlewares/OpenAMP/libmetal/generic/generic_shmem.d ./Middlewares/OpenAMP/libmetal/generic/generic_shmem.o ./Middlewares/OpenAMP/libmetal/generic/generic_shmem.su ./Middlewares/OpenAMP/libmetal/generic/time.cyclo ./Middlewares/OpenAMP/libmetal/generic/time.d ./Middlewares/OpenAMP/libmetal/generic/time.o ./Middlewares/OpenAMP/libmetal/generic/time.su

.PHONY: clean-Middlewares-2f-OpenAMP-2f-libmetal-2f-generic

